title: Familia Guerra 
description: Recopilatorio geneal√≥gico
show_downloads: false


google_analytics: # optional tracking ID
remote_theme: pages-themes/merlot@v0.2.0
plugins:
  - jekyll-remote-theme
